export const TITLE = "[DEV] DemBeck Coding";
export const MAPS_API_KEY = "AIzaSyBRaiMQl0s438GAw20YUdAP-cI9BIOrll8";
export const PHONE_REGEX = "/^(\\+|00|0)[1-9][0-9 \\-\\(\\)\\.\\/\\_]{7,16}$/";
export const GENDERS = [
    "Abinary",
    "Agender",
    "Agenderfluid",
    "Agenderflux",
    "Genderblank",
    "Genderfree",
    "Polyagender",
    "Ambigender",
    "Androgyne",
    "Androgynous",
    "Aporagender",
    "Autigender",
    "Bakla",
    "Bigender",
    "Binary",
    "Bissu",
    "Butch",
    "Calabai",
    "Calalai",
    "Cis",
    "Cisgender",
    "Cis female",
    "Cis male",
    "Cis man",
    "Cis woman",
    "Demi-boy",
    "Demiflux",
    "Demigender",
    "Demi-girl",
    "Demi-guy",
    "Demi-man",
    "Demi-woman",
    "Dual gender",
    "Eunuch",
    "Fa'afafine",
    "Female",
    "Female to male",
    "Femme",
    "FTM",
    "Gender bender",
    "Gender diverse",
    "Gender gifted",
    "Genderfae",
    "Genderfluid",
    "Genderflux",
    "Genderfuck",
    "Genderless",
    "Gender nonconforming",
    "Genderqueer",
    "Gender questioning",
    "Gender variant",
    "Graygender",
    "Hijra",
    "Intergender",
    "Intersex",
    "Ipsogender",
    "Kathoey",
    "Māhū",
    "M3A3 Bradly",
    "Male",
    "Male to female",
    "Man",
    "Man of trans experience",
    "Maverique",
    "Meta-gender",
    "MTF",
    "Multigender",
    "Muxe",
    "Naruto",
    "Neither",
    "Neurogender",
    "Neutrois",
    "non-binary",
    "Non-binary transgender",
    "Omnigender",
    "Other",
    "Pangender",
    "Person of transgendered experience",
    "Polygender",
    "Prefer not to say",
    "Queer",
    "Sekhet",
    "Third gender",
    "Trans",
    "Trans*",
    "Trans female",
    "Trans male",
    "Trans man",
    "Trans person",
    "Trans woman",
    "Transgender",
    "Transgender female",
    "Transgender male",
    "Transgender man",
    "Transgender person",
    "Transgender woman",
    "Transfeminine",
    "Transmasculine",
    "Transsexual",
    "Transsexual female",
    "Transsexual male",
    "Transsexual man",
    "Transsexual person",
    "Transsexual woman",
    "Travesti",
    "Trigender",
    "Tumtum",
    "Two spirit",
    "Vakasalewalewa",
    "Waria",
    "Winkte",
    "Woman",
    "Woman of trans experience",
    "X-gender",
    "X-jendā",
    "Xenogender"
]