name: Build and Deploy Angular App
on:
  push:
    branches:
      - feature/*
      - dev
      - uat
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Set ENV based on branch
        run: |
          BRANCH="${{ github.ref_name }}"
          echo "Branch is $BRANCH"

          # If branch is "dev" OR it matches the pattern of digits followed by a dash and more characters
          if [[ "$BRANCH" == "dev" || "$BRANCH" =~ feature/* ]]; then
            echo "ENV=dev" >> $GITHUB_ENV

          # If branch is "uat"
          elif [[ "$BRANCH" == "uat" ]]; then
            echo "ENV=uat" >> $GITHUB_ENV

          # If branch is "prod"
          elif [[ "$BRANCH" == "prod" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV

          # Fallback if something else slips through
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Build Angular App
        run: | 
          npm run build:$ENV
      
      # Upload dist folder as an artifact
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist  # Adjust if your project places compiled files in a deeper folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download the dist artifact from the build job
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Branch to deploy to.
          folder: /home/runner/work/my-bill/dist # build directory
          token: ${{ secrets.GH_TOKEN }}
