name: Build and Deploy Angular App
on:
  push:
    branches:
      - '\d+-[a-z0-9\-]+'
      - dev
      - uat
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: | 
          BRANCH=${GITHUB_REF##*/}
          echo "Building for branch: $BRANCH"
          npm run build:$BRANCH

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages             # Branch to deploy to.
          folder: dist
          token: ${{ secrets.GH_TOKEN }}
